import { StyleSheet } from "react-native";

export const ProfileStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  contentContainer: {
    paddingBottom: 40,
  },
  header: {
    height: 320,
    position: "relative",
    overflow: "hidden",
  },
  headerGradient: {
    flex: 1,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  profileSection: {
    alignItems: "center",
    zIndex: 2,
    paddingBottom: 30,
  },
  userBadge: {
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 25,
    marginTop: 16,
    alignItems: "center",
    backdropFilter: "blur(10px)",
  },
  userBadgeText: {
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 4,
    textAlign: "center",
  },
  userRoleText: {
    fontSize: 13,
    fontWeight: "500",
    textAlign: "center",
    opacity: 0.9,
  },
  headerTopBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    paddingHorizontal: 20,
    paddingTop: 50,
    paddingBottom: 10,
    zIndex: 3,
  },
  themeToggleContainer: {
    zIndex: 3,
  },
  profileTitleContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 15,
  },
  profileTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: "#ffffff",
    textShadowColor: "rgba(0,0,0,0.3)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  logoutButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    justifyContent: "center",
    alignItems: "center",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  logoutButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#ffffff",
  },
  avatarContainer: {
    position: "relative",
    marginBottom: 16,
  },
  avatar: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 4,
    borderColor: "#ffffff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 12,
  },
  statusDot: {
    position: "absolute",
    bottom: 8,
    right: 8,
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 3,
    borderColor: "#ffffff",
  },
  name: {
    fontSize: 28,
    fontWeight: "800",
    marginBottom: 4,
    textAlign: "center",
    letterSpacing: 0.5,
    textShadowColor: "rgba(0,0,0,0.3)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  subtitle: {
    fontSize: 16,
    fontWeight: "500",
    letterSpacing: 0.3,
  },
  cardsContainer: {
    paddingHorizontal: 20,
    paddingTop: 20,
    gap: 20,
  },
  infoCard: {
    borderRadius: 20,
    padding: 24,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 6,
    borderWidth: 1,
  },
  skillCard: {
    borderRadius: 20,
    padding: 24,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 6,
    borderWidth: 1,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  iconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  icon: {
    fontSize: 20,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "700",
    letterSpacing: 0.3,
  },
  cardContent: {
    gap: 8,
  },
  infoText: {
    fontSize: 15,
    lineHeight: 22,
    letterSpacing: 0.2,
  },
  skillGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  skillBadge: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  skillText: {
    fontSize: 14,
    fontWeight: "600",
    letterSpacing: 0.2,
  },
  authInfo: {
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    padding: 16,
    borderRadius: 12,
    marginBottom: 16,
    alignItems: "center",
  },
  welcomeText: {
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
    letterSpacing: 0.3,
    marginBottom: 4,
  },
  userInfo: {
    fontSize: 14,
    fontWeight: "500",
    textAlign: "center",
    opacity: 0.8,
  },
  
  // Stats Container
  statsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 20,
    gap: 12,
  },
  statCard: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 20,
    alignItems: "center",
    borderWidth: 1,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  statNumber: {
    fontSize: 24,
    fontWeight: "800",
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    fontWeight: "600",
    textAlign: "center",
    lineHeight: 16,
  },
  
  // Goal Items
  goalItem: {
    marginBottom: 8,
  },
  goalText: {
    fontSize: 15,
    lineHeight: 22,
    letterSpacing: 0.2,
  },
  floatingElement1: {
    position: "absolute",
    top: 100,
    right: -30,
    width: 80,
    height: 80,
    borderRadius: 40,
    opacity: 0.1,
  },
  floatingElement2: {
    position: "absolute",
    top: 200,
    left: -40,
    width: 60,
    height: 60,
    borderRadius: 30,
    opacity: 0.1,
  },
  floatingElement3: {
    position: "absolute",
    bottom: 100,
    right: -20,
    width: 100,
    height: 100,
    borderRadius: 50,
    opacity: 0.08,
  },
});
